### ISSUE TITLE
Store training parameters

### ISSUE THREAD

**Issue by noragalvin** [dathoangnd/gonet#4]
**Is your feature request related to a problem? Please describe.**
I would like to save the number of iteration, learning rate and momentum factor in NN struct and can export to JSON file

**Describe the solution you'd like**
Add fields to NN struct to store training parameters.

**Comment by dathoangnd** [comment]
Hi noragalvin,
Thanks for your suggestion.
I will consider adding this feature to the library.
In case you want to contribute to this project, please make a fork and create a pull request.
Cheers.
